### PR TITLE
Add support for CS9 controller

### PR DESCRIPTION
**Pull request by marshallpowell97**
Separate out the UI code for CS8 and CS9 into libraries. Library is loaded at runtime depending on version of controller (done automatically). Same code base can still be used for both controllers.

Relevant: https://github.com/ros-industrial/staubli_val3_driver/issues/4

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This is quite a nice PR. Thanks for this @marshallpowell97 :+1: 

@gonzalocasas: would you happen to see any possibility to test this? Perhaps in SRS? It's OK if you don't. I only have a (rather) old version of it which doesn't support CS9 controllers.

**Comment by simonschmeisser** [comment]
I unfortunately don't have access to a Stäubli myself and I think our customer doesn't have one either at the moment. Maybe @marshallpowell97 could motivate someone at Stäubli to update your license for SRS?

**Comment by gonzalocasas** [comment]
I will test it, I received the SRS license dongle from our office, so, I can now test at home.

**Comment by gavanderhoorn** [comment]
@gonzalocasas wrote:
> I will test it, I received the SRS license dongle from our office, so, I can now test at home.

awesome, thanks @gonzalocasas :+1:

**Comment by gavanderhoorn** [comment]
@gonzalocasas: I hate to be pushy, but I don't want to keep @marshallpowell97 waiting too long.

Would you happen to have some time next week to test this PR?

**Comment by gonzalocasas** [comment]
I just tried on my SRS, but despite being CS9, it still complains about trying to load CS8 stuff:

image

@marshallpowell97: do I need to do something additional to get it to ignore these incompatible data types?

**Comment by gonzalocasas** [comment]
Also, unless I'm looking at the wrong branch, `ros_server.dtx` still contains the `scDebug`, and `scMonitor` variables that are of the incompatible data type, which was the problem in the first place.

**Comment by gonzalocasas** [comment]
@marshallpowell97 @gavanderhoorn if I remove the two variables leftover `screen` type variables from `ros_server.dtx` and I update the path of the library in `ros_server.pjx` to point to `interfaceCS9` then everything else seems to work fine.

**Comment by gavanderhoorn** [comment]
Thanks for testing @gonzalocasas.

The idea would certainly be for this to all be detected and switched automatically, so what you describe seems like a problem with the current code.

**Comment by gavanderhoorn** [comment]
Friendly ping @marshallpowell97.

**Comment by marshallpowell97** [comment]
> ros_server.dtx still contains the scDebug, and scMonitor variables that are of the incompatible data type, which was the problem in the first place.

This was an oversight on my part, I removed them. They are now only in interfaceCS8.dtx where they should be.

I also noticed another issue that didn't show up on a real controller (since I don't have access to any of our robots at the moment). Even when the 'auto load' option for the library `libInterface` is deselected, it still causes a runtime error when using the emulator in SRS. I added another interface library `interfaceDefault` which is empty and loads fine on either controller.

**Comment by gavanderhoorn** [comment]
@gonzalocasas: would you perhaps happen to have some time to test this?

I'd like to merge it, but it would be good to have a second pair of eyes on the functionality @marshallpowell97 has added.

**Comment by gonzalocasas** [comment]
@gavanderhoorn yes, I had it in my radar already, but haven't had the time so far. But I will test it in the coming days!

**Comment by gavanderhoorn** [comment]
Ping @gonzalocasas ?

**Comment by gavanderhoorn** [comment]
I'm going to merge this to not delay @marshallpowell97 any longer.

We'll deal with problems with this change in follow-up PRs.

**Pull request merged**
